Speed up prepare-features
r9y9/nnsvs pull request #50
Opened 2021-08-29 06:22 UTC by oatsu-gh

For a large singing-databese, preparing features can be the 1st or 2nd bottleneck in training. I tried to make it faster.

- Speed up prepare-features by multi-threading using `joblib.Parallel()`
- Use `logger.info(OmegaConf.to_yaml(config))` instead of `logger.info(config.pretty())` for keeping up with omegaconf>=1.1
- Remove unused imports

2021-08-31 06:39 UTC, r9y9 commented
Sorry for the late reply. I have been busy at work. I will get to review once I get some time!

2021-09-06 14:03 UTC, r9y9 requested changes
Thanks for the PR!  I have two requests to make the code better. Please check my inline comments.

2021-09-06 14:03 UTC, r9y9 commented on nnsvs/bin/prepare_features.py
> +        )
Could you replace `joblib.Parallel` to `concurrent.futures.ProcessPoolExecutor`? The later is more tqdm friendly. We cannot easily make tqdm work if we use joblib.Parallel.

You can refer to my another repository: https://github.com/r9y9/ttslearn/blob/23a4088571ac680f7e28b6ac59d3e2eb31b9511f/recipes/dnntts/preprocess_acoustic.py#L95-L110

2021-09-06 14:03 UTC, r9y9 commented on nnsvs/bin/prepare_features.py
> +        )
Also, it would be nice if we add `n_jobs` in config.yaml so that we can control it through the CLI (i.e., run.sh or prepare_features.py).

2021-09-06 14:03 UTC, r9y9 commented on nnsvs/bin/prepare_features.py
Same as above

2021-09-06 14:03 UTC, r9y9 commented on nnsvs/bin/prepare_features.py
> +
Same as above

2021-09-06 14:05 UTC, r9y9 commented
BTW, we can ignore CI errors. I will fix pysinsy https://github.com/r9y9/pysinsy/issues/6 and CI accordingly.

2021-09-07 12:34 UTC, r9y9 commented
Done fixing the pysinsy and CI issues (https://github.com/r9y9/nnsvs/pull/51). You can fix CI by merging or rebasing on master.

2021-09-25 09:46 UTC, oatsu-gh commented
Sorry for having you wait so long. I've just learned about git rebasing. Now I'm learning `concurrent.futures.ProcessPoolExecutor` and developing the codes above. Thank you.

2021-09-25 09:48 UTC, oatsu-gh commented
誤って re-review をリクエストしてしまいました。無視していただけますと幸いです。

2021-09-25 12:55 UTC, oatsu-gh commented
- In prepare_features, Changed to use `ProcessPoolExecutor` with `config.max_workers`.
  - What do you think about the config name "max_workers"? Would it be better to use "n_jobs" or "num_workers" than "max_workers"?
- Added a new line `max_workers: none` into bin/conf/prepare_features/config.yaml.

2021-09-26 07:43 UTC, r9y9 reviewed
Added a few comments. The name `max_workers` looks good to me.

2021-09-26 07:43 UTC, r9y9 commented on nnsvs/bin/prepare_features.py
> +    if config.timelag.enabled:
```suggestion
    if config.duration.enabled:
```

2021-09-26 07:43 UTC, r9y9 commented on nnsvs/bin/prepare_features.py
> +    if config.timelag.enabled:
```suggestion
    if config.acoustic.enabled:
```

2021-09-26 07:43 UTC, r9y9 commented on nnsvs/bin/prepare_features.py
> +    # Save features for duration model
```suggestion
    # Save features for acoustic model
```

2021-09-27 03:13 UTC, oatsu-gh commented
Thank you for the checking and fixing!

2021-09-27 03:22 UTC, r9y9 approved these changes
LGTM, thank you!

2021-09-27 03:22 UTC, merged